config/routes.rb
Rails.application.routes.draw do

  resources :filtros
  resources :representantes
  resources :alerta
  resources :recibos
  resources :vehiculos
  resources :clientes do
    collection do
      get :filtered, as: :filtro
    end
  end

  root to: 'layouts#index'
  get 'clientes'          => 'clientes#index',    as: :reporte_cliente
  get 'clientes/new'      => 'clientes#new',      as: :nuevo_cliente
  get 'vehiculos'         => 'vehiculos#index',   as: :reporte_vehiculo
  get 'vehiculos/new'     => 'vehiculos#new',     as: :nuevo_vehiculo
  get 'recibos'           => 'recibos#index',     as: :reporte_recibo
  get 'recibos/new'       => 'recibos#new',       as: :nuevo_recibo
  get 'alerta'            => 'alerta#index',      as: :reporte_alerta
  get 'alerta/new'        => 'alerta#new',        as: :nuevo_alerta
  get 'solicitud'         => 'layouts#solicitud', as: :solicitud
  get 'filtros/new'       => 'filtros#new',       as: :nuevo_filtro

  Rails.application.routes.draw do
    resources :filtros
    resources :alerta
    resources :recibos
    devise_for :users, :controllers =>  { :registrations => "my_devise/registrations" }
  end

end

app/models/cliente.rb
class Cliente < ApplicationRecord

  def calcula_ahorro
    # arrvehiculos = arreglo de todos los vehículos que son de un tal cliente
    arrvehiculos = Vehiculo.where(:credencialcliente_vehiculo => credencial_cliente).order(:id)
    # i = contador que recorre el arreglo arrvehiculos
    i = 0
    # ahorro = variable que regresa el método en la que se almacena la sumatoria de ahorros
    ahorro = 0

    while i < arrvehiculos.length
      vehiculo = arrvehiculos[i]

      # arrrecibos = arreglo de todos los recibos de un tal vehículo
      arrrecibos = Recibo.where(:placas_recibo => arrvehiculos[i].placas_vehiculo).order(:id)
      # j = contador que recorre el arreglo de arrrecibos
      j = 0

      while j < arrrecibos.length - 1
        kmA = arrrecibos[j].kmactual_recibo
        kmB = arrrecibos[j+1].kmactual_recibo
        litros = arrrecibos[j].combustible_recibo
        precio = arrrecibos[j].preciogas_recibo
        ahorro = ahorro + (((kmB - kmA)/arrvehiculos[i].rendimientohistorico_vehiculo)-litros)*precio
        j = j + 1
      end

      i = i + 1
    end

    ahorro
    @a = ahorro

  end

  def calcula_pComisionista
    part = (@a * 0.50) * (porcentage_cliente/100)
  end

  def calcula_pOTS
    part = (@a * 0.50) * (1-(porcentage_cliente/100))
  end

  def calcula_ahorro_filtrado
    # arrvehiculos = arreglo de todos los vehículos que son de un tal cliente
    arrvehiculos = Vehiculo.where(:credencialcliente_vehiculo => credencial_cliente).order(:id)
    # i = contador que recorre el arreglo arrvehiculos
    i = 0
    # ahorro = variable que regresa el método en la que se almacena la sumatoria de ahorros
    ahorro = 0

    while i < arrvehiculos.length
      vehiculo = arrvehiculos[i]

      # arrrecibos = arreglo de todos los recibos de un tal vehículo
      arrrecibos = Recibo.where(:placas_recibo => arrvehiculos[i].placas_vehiculo).where("created_at >= ? AND created_at < ?", Filtro.last.fechainicio_filtro.to_date, Filtro.last.fechafin_filtro.to_date).order(:id)
      # j = contador que recorre el arreglo de arrrecibos
      j = 0

      while j < arrrecibos.length - 1
        kmA = arrrecibos[j].kmactual_recibo
        kmB = arrrecibos[j+1].kmactual_recibo
        litros = arrrecibos[j].combustible_recibo
        precio = arrrecibos[j].preciogas_recibo
        ahorro = ahorro + (((kmB - kmA)/arrvehiculos[i].rendimientohistorico_vehiculo)-litros)*precio
        j = j + 1
      end

      i = i + 1
    end

    ahorro
    @b = ahorro

  end

  def calcula_pComisionista_filtrado
    part = (@b * 0.50) * (porcentage_cliente/100)
  end

  def calcula_pOTS_filtrado
    part = (@b * 0.50) * (1-(porcentage_cliente/100))
  end


  def calcula_terceros
    arrteceros = Vehiculo.where(:credencialcliente_vehiculo => credencial_cliente).order(:tercero_vehiculo)
    @t = arrteceros.uniq
  end

end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  def filtered
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:credencial_cliente, :empresa_cliente, :responsable_cliente, :telefono_cliente, :email_cliente, :comisionista_cliente, :porcentage_cliente)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<div class="row">
  <div class="col-md-4 offset-md-4" style="text-align: center">

    <%= form_for(cliente, html: {class: "form-signin"}) do |f| %>

      <% if cliente.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

          <ul>
            <% cliente.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <h2>Cliente nuevo</h2>
      <br>
      <div class="field">
        <%= f.label :credencial_cliente, class: 'sr-only' %>
        <%= f.text_field :credencial_cliente, class: 'form-control', placeholder: 'Credencial del cliente' %>
      </div>
      <br>
      <div class="field">
        <%= f.label :empresa_cliente, class: 'sr-only' %>
        <%= f.text_field :empresa_cliente, class: 'form-control', placeholder: 'Nombre de la empresa' %>
      </div>
      <br>
      <div class="field">
        <%= f.label :responsable_cliente, class: 'sr-only' %>
        <%= f.text_field :responsable_cliente, class: 'form-control', placeholder: 'Nombre del responsable' %>
      </div>
      <br>
      <div class="field">
        <%= f.label :telefono_cliente, class: 'sr-only' %>
        <%= f.phone_field :telefono_cliente, class: 'form-control', placeholder: 'Teléfono' %>
      </div>
      <br>
      <div class="field">
        <%= f.label :email_cliente, class: 'sr-only' %>
        <%= f.text_field :email_cliente, class: 'form-control', placeholder: 'Correo electrónico' %>
      </div>
      <br>
      <div class="field">
        <%= f.label :comisionista_cliente, class: 'sr-only' %>
        <%= f.text_field :comisionista_cliente, class: 'form-control', placeholder: 'Nombre del comisionista' %>
      </div>
      <br>
      <div class="field">
        <%= f.label :porcentage_cliente, class: 'sr-only' %>
        <%= f.number_field :porcentage_cliente, class: 'form-control', placeholder: 'Porcentaje para el comisionista' %>
      </div>
      <br>
      <div class="actions">
        <%= f.submit "Crear", class: 'btn btn-lg btn-primary' %>
      </div>

    <% end %>

  </div>
</div>

app/views/clientes/edit.html.erb
<%= render 'layouts/navbar' %>
<% if current_user && current_user.AdminStatus? %>
  <%= render 'form', cliente: @cliente %>
  <%= link_to 'Show', @cliente %> |
  <%= link_to 'Back', clientes_path %>
<% else %>
  <%= render 'layouts/error' %>
<% end %>

app/views/clientes/filtered.html.erb
<%= render 'layouts/navbar' %>
<% if current_user && current_user.AdminStatus? %>
<div class="row">
  <div class="col-md-10 offset-md-1">
    <%= button_to "Generar PDF", "/recibos.pdf", method: :get, class: 'btn btn-lg btn-primary' %>

    <% @cliente = Cliente.where(:credencial_cliente => Filtro.last.empresa_filtro).first %>
    <h1 style="text-align:center"> <%= @cliente.empresa_cliente %> </h1>
    <table class="table table-responsive">
      <thead>
        <tr>
          <th>Ahorro</th>
          <th>Participación OTS</th>
          <th>Participación comisionista</th>
          <th>Sobres aplicados</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th><%= @cliente.calcula_ahorro_filtrado.round(2)%></th>
          <th><%= @cliente.calcula_pOTS_filtrado.round(2)%></th>
          <th><%= @cliente.calcula_pComisionista_filtrado.round(2)%></th>
          <th><%= Recibo.where(:placas_recibo => Vehiculo.where(:credencialcliente_vehiculo => @cliente.credencial_cliente).pluck(:placas_vehiculo)).sum(:sobres_recibo) %></th>
        </tr>
      </tbody>
    </table>
    <br>
    <div class="offset-md-1">
      <% @vehiculo = Vehiculo.where(:credencialcliente_vehiculo => @cliente.credencial_cliente) %>
      <% @vehiculo.each do |vehiculo| %>
        <table class="table table-responsive">
          <tr>
            <td><%= vehiculo.marca_vehiculo %></td>
            <td><%= vehiculo.modelo_vehiculo %></td>
            <td><%= vehiculo.ano_vehiculo %></td>
            <td><%= vehiculo.placas_vehiculo %></td>
          </tr>
        </table>

        <div class="offset-md-1">
          <table class="table table-responsive">
            <thead>
              <tr>
                <td>Folio</td>
                <td>Kilometraje</td>
                <td>Combustible</td>
                <td>Sobres aplicados</td>
                <td>Fecha</td>
              </tr>
            </thead>
            <% @recibo = Recibo.where(:placas_recibo => vehiculo.placas_vehiculo).where("created_at >= ? AND created_at < ?", Filtro.last.fechainicio_filtro.to_date, Filtro.last.fechafin_filtro.to_date) %>
            <% @recibo.each do |recibo| %>
            <tbody>
              <tr>
                <td><%= recibo.id %></td>
                <td><%= recibo.kmactual_recibo %></td>
                <td><%= recibo.combustible_recibo %></td>
                <td><%= recibo.sobres_recibo %></td>
                <td><%= recibo.created_at.strftime("%e / %b / %Y") %></td>
              </tr>
            </tbody>
            <% end %>
          </table>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% else %>
  <%= render 'layouts/error' %>
<% end %>

app/views/clientes/index.html.erb
<%= render 'layouts/navbar' %>
<% if current_user && current_user.AdminStatus? %>

<div class="row">
  <div class="col-md-2 offset-md-1">
    <%= button_to "Filtrar", nuevo_filtro_path, method: :get, class: 'btn btn-lg btn-primary' %>
  </div>
  <div class="col-md-6">
    <h2 style="text-align:center">Clientes</h2>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-10 offset-md-1">
    <table class="table table-responsive">
      <thead>
        <tr>
          <th>Credencial</th>
          <th>Empresa</th>
          <th>Ahorro</th>
          <th>Participación OTS</th>
          <th>Participación comisionista</th>
          <th>Sobres aplicados</th>
          <th>Detalles</th>
          <th>Eliminar</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody style="text-align:center">
        <% @clientes.each do |cliente| %>
        <tr>
          <td><%= cliente.credencial_cliente%></td>
          <td><%= cliente.empresa_cliente %></td>
          <td>$ <%= cliente.calcula_ahorro.round(2) %></td>
          <td>$ <%= cliente.calcula_pOTS.round(2) %></td>
          <td>$ <%= cliente.calcula_pComisionista.round(2) %></td>
          <td><%= Recibo.where(:placas_recibo => Vehiculo.where(:credencialcliente_vehiculo => cliente.credencial_cliente).pluck(:placas_vehiculo)).sum(:sobres_recibo) %></td>
          <td><%= link_to '', cliente, class: 'btn btn-info'%></td>
          <td><%= link_to '', cliente, class: 'btn btn-danger', method: :delete, data: { confirm: '¿Estás seguro de eliminar a este cliente?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<% else %>
  <%= render 'layouts/error' %>
<% end %>

app/views/clientes/new.html.erb
<%= render 'layouts/navbar' %>
<% if current_user && current_user.AdminStatus? %>
  <%= render 'form', cliente: @cliente %>
<% else %>
  <%= render 'layouts/error' %>
<% end %>

app/views/clientes/show.html.erb
<%= render 'layouts/navbar' %>
<% if current_user && current_user.AdminStatus? %>
  <div class="row">
    <div class="col-md-4 offset-md-4" style="text-align: center">
      <h4><%= @cliente.empresa_cliente %></h4>

      <table class="table">
        <tr>
          <td>
            <strong>Credencial</strong>
          </td>
          <td>
            <p><%= @cliente.credencial_cliente %></p>
          </td>
        </tr>
        <tr>
          <td>
            <strong>Contacto</strong>
          </td>
          <td>
            <p><%= @cliente.responsable_cliente %></p>
          </td>
        </tr>
        <tr>
          <td>
            <strong>Teléfono</strong>
          </td>
          <td>
            <p><%= @cliente.telefono_cliente %></p>
          </td>
        </tr>
        <tr>
          <td>
            <strong>Correo electrónico</strong>
          </td>
          <td>
            <p><%= @cliente.email_cliente %></p>
          </td>
        </tr>
        <tr>
          <td>
            <strong>Comisionista</strong>
          </td>
          <td>
            <p><%= @cliente.comisionista_cliente %></p>
          </td>
        </tr>
        <tr>
          <td>
            <strong>Porcentaje</strong>
          </td>
          <td>
            <p><%= @cliente.porcentage_cliente %></p>
          </td>
        </tr>
      </table>
      <%= link_to 'Editar', edit_cliente_path(@cliente), class: 'btn btn-warning' %>
    </div>
  </div>
  <br>
  <br>
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <table class="table table-responsive">
        <thead>
          <tr>
            <th>Placas</th>
            <th>Operador vehiculo</th>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Rendimiento</th>
            <th>Ahorro</th>
            <th>Litros Cargados</th>
            <th>Detalles</th>
            <th>Eliminar</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody style="text-align:center">
          <% Vehiculo.where(:credencialcliente_vehiculo => @cliente.credencial_cliente).each do |vehiculo| %>
          <tr>
            <td><%= vehiculo.placas_vehiculo %></td>
            <td><%= vehiculo.operador_vehiculo %></td>
            <td><%= vehiculo.marca_vehiculo %></td>
            <td><%= vehiculo.modelo_vehiculo %></td>
            <td></td>
            <td></td>
            <td><%= Recibo.where(:placas_recibo => vehiculo.placas_vehiculo).sum(:combustible_recibo) %></td>
            <td><%= link_to '', vehiculo, class: 'btn btn-info' %></td>
            <td><%= link_to '', vehiculo, method: :delete, data: { confirm: '¿Estás seguro de eliminar este vehículo?' }, class: 'btn btn-danger' %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
  <%= render 'layouts/error' %>
<% end %>