config/routes.rb
Rails.application.routes.draw do

  resources :filtros
  resources :representantes
  resources :alerta
  resources :recibos
  resources :vehiculos
  resources :clientes do
    collection do
      get :filtered, as: :filtro
    end
  end

  root to: 'layouts#index'
  get 'clientes'          => 'clientes#index',    as: :reporte_cliente
  get 'clientes/new'      => 'clientes#new',      as: :nuevo_cliente
  get 'vehiculos'         => 'vehiculos#index',   as: :reporte_vehiculo
  get 'vehiculos/new'     => 'vehiculos#new',     as: :nuevo_vehiculo
  get 'recibos'           => 'recibos#index',     as: :reporte_recibo
  get 'recibos/new'       => 'recibos#new',       as: :nuevo_recibo
  get 'alerta'            => 'alerta#index',      as: :reporte_alerta
  get 'alerta/new'        => 'alerta#new',        as: :nuevo_alerta
  get 'solicitud'         => 'layouts#solicitud', as: :solicitud
  get 'filtros/new'       => 'filtros#new',       as: :nuevo_filtro

  Rails.application.routes.draw do
    resources :filtros
    resources :alerta
    resources :recibos
    devise_for :users, :controllers =>  { :registrations => "my_devise/registrations" }
  end

end

app/models/filtro.rb
class Filtro < ApplicationRecord
end

app/controllers/filtros_controller.rb
class FiltrosController < ApplicationController
  before_action :set_filtro, only: [:show, :edit, :update, :destroy]

  # GET /filtros
  # GET /filtros.json
  def index
    @filtros = Filtro.all
  end

  # GET /filtros/1
  # GET /filtros/1.json
  def show
  end

  # GET /filtros/new
  def new
    @filtro = Filtro.new
  end

  # GET /filtros/1/edit
  def edit
  end

  # POST /filtros
  # POST /filtros.json
  def create
    @filtro = Filtro.new(filtro_params)

    respond_to do |format|
      if @filtro.save
        format.html { redirect_to @filtro, notice: 'Filtro was successfully created.' }
        format.json { render :show, status: :created, location: @filtro }
        redirect_to filtro_clientes_path
        return
      else
        format.html { render :new }
        format.json { render json: @filtro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filtros/1
  # PATCH/PUT /filtros/1.json
  def update
    respond_to do |format|
      if @filtro.update(filtro_params)
        format.html { redirect_to @filtro, notice: 'Filtro was successfully updated.' }
        format.json { render :show, status: :ok, location: @filtro }
      else
        format.html { render :edit }
        format.json { render json: @filtro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filtros/1
  # DELETE /filtros/1.json
  def destroy
    @filtro.destroy
    respond_to do |format|
      format.html { redirect_to filtros_url, notice: 'Filtro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filtro
      @filtro = Filtro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def filtro_params
      params.require(:filtro).permit(:empresa_filtro, :fechainicio_filtro, :fechafin_filtro)
    end
end

app/helpers/filtros_helper.rb
module FiltrosHelper
end

app/views/filtros/_form.html.erb
<div class="row">
  <div class="col-md-4 offset-md-4" style="text-align: center">
    <%= form_for(filtro, html: {class: "form-signin"}) do |f| %>

      <% if filtro.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(filtro.errors.count, "error") %> prohibited this filtro from being saved:</h2>

          <ul>
          <% filtro.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <h2>Filtro</h2>
      <br>
      <div class="field">
        <%= f.label :empresa_filtro, class: 'sr-only' %>
        <%= f.text_field :empresa_filtro, class: 'form-control', placeholder: 'Credencial de la empresa' %>
      </div>
      <br>
      <em>DD-MM-AAAA</em>
      <div class="field">
        <%= f.label :fechainicio_filtro, class: 'sr-only' %>
        <%= f.text_field :fechainicio_filtro, class: 'form-control', placeholder: 'Fecha inicial' %>
      </div>
      <br>
      <div class="field">
        <%= f.label :fechafin_filtro, class: 'sr-only' %>
        <%= f.text_field :fechafin_filtro, class: 'form-control', placeholder: 'Fecha final' %>
      </div>
      <br>
      <div class="actions">
        <%= f.submit "Enviar", class: 'btn btn-lg btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/filtros/edit.html.erb
<% if current_user && current_user.AdminStatus? %>

<h1>Editing Filtro</h1>

<%= render 'form', filtro: @filtro %>

<%= link_to 'Show', @filtro %> |
<%= link_to 'Back', filtros_path %>
<% else %>
<%= render 'layouts/error' %>
<% end %>

app/views/filtros/index.html.erb
<% if current_user && current_user.AdminStatus? %>

<p id="notice"><%= notice %></p>

<h1>Filtros</h1>

<table>
  <thead>
    <tr>
      <th>Empresa filtro</th>
      <th>Fechainicio filtro</th>
      <th>Fechafin filtro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @filtros.each do |filtro| %>
      <tr>
        <td><%= filtro.empresa_filtro %></td>
        <td><%= filtro.fechainicio_filtro %></td>
        <td><%= filtro.fechafin_filtro %></td>
        <td><%= link_to 'Show', filtro %></td>
        <td><%= link_to 'Edit', edit_filtro_path(filtro) %></td>
        <td><%= link_to 'Destroy', filtro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Filtro', new_filtro_path %>
<% else %>
<%= render 'layouts/error' %>
<% end %>

app/views/filtros/new.html.erb
<%= render 'layouts/navbar' %>
<% if current_user && current_user.AdminStatus? %>

<%= render 'form', filtro: @filtro %>
<% else %>
<%= render 'layouts/error' %>
<% end %>

app/views/filtros/show.html.erb
<% if current_user && current_user.AdminStatus? %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Empresa filtro:</strong>
  <%= @filtro.empresa_filtro %>
</p>

<p>
  <strong>Fechainicio filtro:</strong>
  <%= @filtro.fechainicio_filtro %>
</p>

<p>
  <strong>Fechafin filtro:</strong>
  <%= @filtro.fechafin_filtro %>
</p>

<%= link_to 'Edit', edit_filtro_path(@filtro) %> |
<%= link_to 'Back', filtros_path %>
<% else %>
<%= render 'layouts/error' %>
<% end %>