config/routes.rb
Rails.application.routes.draw do

  resources :filtros
  resources :representantes
  resources :alerta
  resources :recibos
  resources :vehiculos
  resources :clientes do
    collection do
      get :filtered, as: :filtro
    end
  end

  root to: 'layouts#index'
  get 'clientes'          => 'clientes#index',    as: :reporte_cliente
  get 'clientes/new'      => 'clientes#new',      as: :nuevo_cliente
  get 'vehiculos'         => 'vehiculos#index',   as: :reporte_vehiculo
  get 'vehiculos/new'     => 'vehiculos#new',     as: :nuevo_vehiculo
  get 'recibos'           => 'recibos#index',     as: :reporte_recibo
  get 'recibos/new'       => 'recibos#new',       as: :nuevo_recibo
  get 'alerta'            => 'alerta#index',      as: :reporte_alerta
  get 'alerta/new'        => 'alerta#new',        as: :nuevo_alerta
  get 'solicitud'         => 'layouts#solicitud', as: :solicitud
  get 'filtros/new'       => 'filtros#new',       as: :nuevo_filtro

  Rails.application.routes.draw do
    resources :filtros
    resources :alerta
    resources :recibos
    devise_for :users, :controllers =>  { :registrations => "my_devise/registrations" }
  end

end

app/models/recibo.rb
class Recibo < ApplicationRecord
end

app/controllers/recibos_controller.rb
class RecibosController < ApplicationController
  before_action :set_recibo, only: [:show, :edit, :update, :destroy]

  # GET /recibos
  # GET /recibos.json
  def index
    @recibos = Recibo.all
    respond_to do |format|
      format.html
      format.json
      format.pdf {render template: 'recibos/reporte', pdf: 'Reporte'}
    end
  end

  # GET /recibos/1
  # GET /recibos/1.json
  def show
  end

  # GET /recibos/new
  def new
    @recibo = Recibo.new
  end

  # GET /recibos/1/edit
  def edit
  end

  # POST /recibos
  # POST /recibos.json
  def create
    @recibo = Recibo.new(recibo_params)
    @recibo.emailrepresentante_recibo = current_user.email
    @recibo.tercero_recibo = Vehiculo.where(:placas_vehiculo => @recibo.placas_recibo).first.tercero_vehiculo
    respond_to do |format|
      if @recibo.save
        if current_user.AdminStatus
          format.html { redirect_to @recibo, notice: 'Recibo creado satisfactoriamente.' }
          format.json { render :show, status: :created, location: @recibo }
        else
          format.html { redirect_to nuevo_recibo_path, notice: 'Recibo creado satisfactoriamente.' }
          format.json { render :show, status: :created, location: @recibo }
        end
      else
        format.html { render :new }
        format.json { render json: @recibo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recibos/1
  # PATCH/PUT /recibos/1.json
  def update
    respond_to do |format|
      if @recibo.update(recibo_params)
        format.html { redirect_to @recibo, notice: 'Recibo was successfully updated.' }
        format.json { render :show, status: :ok, location: @recibo }
      else
        format.html { render :edit }
        format.json { render json: @recibo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recibos/1
  # DELETE /recibos/1.json
  def destroy
    @recibo.destroy
    respond_to do |format|
      format.html { redirect_to recibos_url, notice: 'Recibo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recibo
      @recibo = Recibo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recibo_params
      params.require(:recibo).permit(:folio_recibo, :kmanterior_recibo, :kmactual_recibo, :combustible_recibo, :sobres_recibo, :placas_recibo, :preciogas_recibo, :created_at, :tercero_recibo)
    end
end

app/helpers/recibos_helper.rb
module RecibosHelper
end

app/views/recibos/_form.html.erb
<div class="row">
  <div class="col-md-4 offset-md-4" style="text-align: center">
    <%= form_for(recibo, html: {class: "form-signin"}) do |f| %>

      <% if recibo.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(recibo.errors.count, "error") %> prohibited this recibo from being saved:</h2>

        <ul>
          <% recibo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <h2>Recibo nuevo</h2>
      <br>
      <div class="field">
        <%= f.label :placas_recibo, class: 'sr-only'%>
        <%= f.text_field :placas_recibo, class: 'form-control', placeholder: 'Placas' %>
      </div>
      <br>
      <div class="field">
        <%= f.label :kmactual_recibo, class: 'sr-only'%>
        <%= f.text_field :kmactual_recibo, class: 'form-control', placeholder: 'Kilometraje actual' %>
      </div>
      <br>
      <div class="field">
        <%= f.label :combustible_recibo, class: 'sr-only' %>
        <%= f.text_field :combustible_recibo, class: 'form-control', placeholder: 'Litros de combustible' %>
      </div>
      <br>
      <div class="field">
        <%= f.label :sobres_recibo, class: 'sr-only' %>
        <%= f.text_field :sobres_recibo, class: 'form-control', placeholder: 'Cantidad de sobres' %>
      </div>
      <br>
      <div class="field">
        <%= f.label :preciogas_recibo, class: 'sr-only' %>
        <%= f.text_field :preciogas_recibo, class: 'form-control', placeholder: 'Precio actual del combustible' %>
      </div>

      <br>
      <% if current_user && current_user.AdminStatus? %>

      <div class="field">
        <%= f.label :created_at, class: 'sr-only' %>
        <%= f.date_field :created_at, class: 'form-control', placeholder: 'Fecha de recibo' %>
      </div>
      <br>
      <% end %>

      <div class="actions">
        <%= f.submit "Crear", class: 'btn btn-lg btn-primary' %>
      </div>

    <% end %>
  </div>
</div>

app/views/recibos/edit.html.erb
<%= render 'layouts/navbar' %>
<% if current_user && current_user.AdminStatus? %>
  <%= render 'form', recibo: @recibo %>
  <%= link_to 'Show', @recibo %> |
  <%= link_to 'Back', recibos_path %>
<% else %>
  <%= render 'layouts/error' %>
<% end %>

app/views/recibos/index.html.erb
<%= render 'layouts/navbar' %>
<% if current_user && current_user.AdminStatus? %>
  <div class="row">
  <div class="col-md-10 offset-md-1">
    <h2 style="text-align:center">Recibos</h2>
    <br>
    <table class="table table-responsive"  style="text-align:center">
      <tbody style="text-align:center">
        <tr>
          <th>Folio recibo</th>
          <th>Placas</th>
          <th>Compañía</th>
          <th>Kilometraje</th>
          <th>Combustible</th>
          <th>Sobres aplicados</th>
          <th>Precio del combustible</th>
          <th>Detalles</th>
          <th>Eliminar</th>
          <th colspan="3"></th>
        </tr>
        <% @recibos.each do |recibo| %>
        <tr>
          <td><%= recibo.id %></td>
          <th><%= recibo.placas_recibo %></th>
          <th><%= Cliente.where(:credencial_cliente => Vehiculo.where(:placas_vehiculo => recibo.placas_recibo).first.credencialcliente_vehiculo).first.empresa_cliente %></th>
          <td><%= recibo.kmactual_recibo %></td>
          <td><%= recibo.combustible_recibo %></td>
          <td><%= recibo.sobres_recibo %></td>
          <td><%= recibo.preciogas_recibo %></td>
          <td><%= link_to '', recibo, class: 'btn btn-info' %></td>
          <td><%= link_to '', recibo, method: :delete, data: { confirm: '¿Estás seguro de eliminar este recibo?' }, class: 'btn btn-danger' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <br>
  </div>
</div>
<% else %>
  <%= render 'layouts/error' %>
<% end %>

app/views/recibos/new.html.erb
<%= render 'layouts/navbar' %>
<% if current_user %>
  <%= render 'form', recibo: @recibo %>
<% else %>
  <%= render 'layouts/error' %>
<% end %>

app/views/recibos/reporte.pdf.erb
<%= wicked_pdf_stylesheet_link_tag "pdf.css" -%>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>

  <body>

      <!-- Reporte mensual -->
      <div class="row">
        <div class="col-xs-12">
        </div>
        <br>
      </div>
      <!-- Información esencial y logo -->
      <div class="row">
        <div class="col-xs-6">
          <h1>Reporte Mensual</h1>
          <% @cliente = Cliente.where(:credencial_cliente => Filtro.last.empresa_filtro).first %>
          <h2> <%= @cliente.empresa_cliente %> </h2>
          <br>
          <table class="center table table-responsive">
            <tr bgcolor="#97d700">
              <td><strong>Ahorro</strong></td>
              <td>$ <%= @cliente.calcula_ahorro_filtrado.round(2)%> <%=%></td>
            </tr>
            <tr>
              <td><strong>Total a pagar</strong></td>
              <% @total = @cliente.calcula_ahorro_filtrado.round(2)/2 %>
              <td>$ <%= @total.round(2)%></td>
            </tr>
            <tr>
              <td><strong>Periodo</strong></td>
              <td><%= Filtro.last.fechainicio_filtro.to_date.strftime("%e/%b/%Y") %>  -  <%= Filtro.last.fechafin_filtro.to_date.strftime("%e/%b/%Y") %></td>
            </tr>
          </table>
        </div>
        <div class="col-xs-6 image_space">
          <%= wicked_pdf_image_tag ("pdflogo.png"), :class => "image_center" %>
        </div>
      </div>
      <!-- Desglosado de los recibos -->
      <div class="row">
        <div class="col-xs-12">
          <br>
          <% @vehiculo = Vehiculo.where(:credencialcliente_vehiculo => @cliente.credencial_cliente) %>
          <% @vehiculo.each do |vehiculo| %>
            <table class="table table-responsive">
              <tr bgcolor="#97d700">
                <td><strong><%= vehiculo.placas_vehiculo %></strong></td>
                <td><strong><%= vehiculo.marca_vehiculo %></strong></td>
                <td><strong><%= vehiculo.modelo_vehiculo %></strong></td>
                <td><strong><%= vehiculo.ano_vehiculo %></strong></td>
              </tr>
            </table>
            <table class="table table-responsive">
              <tr>
                <td>Folio</td>
                <td>Kilometraje</td>
                <td>Combustible</td>
                <td>Sobres aplicados</td>
                <td>Fecha</td>
              </tr>
              <% @recibo = Recibo.where(:placas_recibo => vehiculo.placas_vehiculo).where("created_at >= ? AND created_at < ?", Filtro.last.fechainicio_filtro.to_date, Filtro.last.fechafin_filtro.to_date) %>
              <% @recibo.each do |recibo| %>
                <tr>
                  <td><%= recibo.id %></td>
                  <td><%= recibo.kmactual_recibo %></td>
                  <td><%= recibo.combustible_recibo %></td>
                  <td><%= recibo.sobres_recibo %></td>
                  <td><%= recibo.created_at.strftime("%e / %b / %Y") %></td>
                </tr>
              <% end %>
            </table>

          <% end %>
        </div>
      </div>

  </body>

app/views/recibos/show.html.erb
<%= render 'layouts/navbar' %>
<% if current_user && current_user.AdminStatus? %>
  <div class="row" style="text-align: center">
  <!-- División de información de recibo -->
  <div class="col-md-3">
    <h4>Recibo</h4>
    <table class="table">
      <tr>
        <td>
          <strong>Folio</strong>
        </td>
        <td>
          <strong><%= @recibo.id %></strong>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Fecha</strong>
        </td>
        <td>
          <%= @recibo.created_at.strftime("%e / %b / %Y") %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Kilometraje actual</strong>
        </td>
        <td>
          <p><%= @recibo.kmactual_recibo %></p>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Combustible</strong>
        </td>
        <td>
          <p><%= @recibo.combustible_recibo %></p>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Precio combustible</strong>
        </td>
        <td>
          <p>$ <%= @recibo.preciogas_recibo %></p>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Cantidad de sobres</strong>
        </td>
        <td>
          <p><%= @recibo.sobres_recibo %></p>
        </td>
      </tr>
    </table>
    <%= link_to 'Editar', edit_recibo_path(@recibo), class: "btn btn-warning" %>
  </div>
  <!-- División de información de representante-->
  <div class="col-md-3">
    <h4>Representante</h4>
    <table class="table">
      <tr>
        <td>
          <strong>Nombre</strong>
        </td>
        <td>
          <%= User.where(:email => @recibo.emailrepresentante_recibo).first.nombre_user %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Correo electrónico</strong>
        </td>
        <td>
          <%= @recibo.emailrepresentante_recibo %>
        </td>
      <tr>
        <td>
          <strong>Teléfono</strong>
        </td>
        <td>
          <%= User.where(:email => @recibo.emailrepresentante_recibo).first.telefono_user %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Ciudad</strong>
        <td>
          <%= User.where(:email => @recibo.emailrepresentante_recibo).first.ciudad_user %>
      </tr>
      <tr>
        <td>
          <strong>Estado</strong>
        <td>
          <%= User.where(:email => @recibo.emailrepresentante_recibo).first.estado_user %>
      </tr>
    </table>
  </div>
  <!-- División de información de vehículo -->
  <div class="col-md-3">
    <h4>Vehículo</h4>
    <table class="table">
      <tr>
        <td>
          <strong>Placas</strong>
        </td>
        <td>
          <%= @recibo.placas_recibo %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Marca</strong>
        </td>
        <td>
          <%= Vehiculo.where(:placas_vehiculo => @recibo.placas_recibo).first.marca_vehiculo %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Modelo</strong>
        </td>
        <td>
          <%= Vehiculo.where(:placas_vehiculo => @recibo.placas_recibo).first.modelo_vehiculo %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Año</strong>
        </td>
        <td>
          <%= Vehiculo.where(:placas_vehiculo => @recibo.placas_recibo).first.ano_vehiculo %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Rendimiento histórico</strong>
        </td>
        <td>
          <%= Vehiculo.where(:placas_vehiculo => @recibo.placas_recibo).first.rendimientohistorico_vehiculo %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Operador</strong>
        </td>
        <td>
          <%= Vehiculo.where(:placas_vehiculo => @recibo.placas_recibo).first.operador_vehiculo %>
        </td>
      </tr>
    </table>
  </div>
  <!-- División de información de cliente -->
  <div class="col-md-3">
    <h4>Cliente</h4>
    <table class="table">
      <tr>
        <td>
          <strong>Credencial del cliente</strong>
        </td>
        <td>
          <%= Vehiculo.where(:placas_vehiculo => @recibo.placas_recibo).first.credencialcliente_vehiculo %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Empresa</strong>
        </td>
        <td>
          <%= Cliente.where(:credencial_cliente => Vehiculo.where(:placas_vehiculo => @recibo.placas_recibo).first.credencialcliente_vehiculo).first.empresa_cliente %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Responsable</strong>
        </td>
        <td>
          <%= Cliente.where(:credencial_cliente => Vehiculo.where(:placas_vehiculo => @recibo.placas_recibo).first.credencialcliente_vehiculo).first.responsable_cliente %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Teléfono</strong>
        </td>
        <td>
          <%= Cliente.where(:credencial_cliente => Vehiculo.where(:placas_vehiculo => @recibo.placas_recibo).first.credencialcliente_vehiculo).first.telefono_cliente %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Correo electrónico</strong>
        </td>
        <td>
          <%= Cliente.where(:credencial_cliente => Vehiculo.where(:placas_vehiculo => @recibo.placas_recibo).first.credencialcliente_vehiculo).first.email_cliente %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Comisionista</strong>
        </td>
        <td>
          <%= Cliente.where(:credencial_cliente => Vehiculo.where(:placas_vehiculo => @recibo.placas_recibo).first.credencialcliente_vehiculo).first.comisionista_cliente %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Porcentaje</strong>
        </td>
        <td>
          <%= Cliente.where(:credencial_cliente => Vehiculo.where(:placas_vehiculo => @recibo.placas_recibo).first.credencialcliente_vehiculo).first.porcentage_cliente %>
        </td>
      </tr>
    </table>
  </div>
</div>
<% else %>
  <%= render 'layouts/error' %>
<% end %>