config/routes.rb
Rails.application.routes.draw do

  resources :filtros
  resources :representantes
  resources :alerta
  resources :recibos
  resources :vehiculos
  resources :clientes do
    collection do
      get :filtered, as: :filtro
    end
  end

  root to: 'layouts#index'
  get 'clientes'          => 'clientes#index',    as: :reporte_cliente
  get 'clientes/new'      => 'clientes#new',      as: :nuevo_cliente
  get 'vehiculos'         => 'vehiculos#index',   as: :reporte_vehiculo
  get 'vehiculos/new'     => 'vehiculos#new',     as: :nuevo_vehiculo
  get 'recibos'           => 'recibos#index',     as: :reporte_recibo
  get 'recibos/new'       => 'recibos#new',       as: :nuevo_recibo
  get 'alerta'            => 'alerta#index',      as: :reporte_alerta
  get 'alerta/new'        => 'alerta#new',        as: :nuevo_alerta
  get 'solicitud'         => 'layouts#solicitud', as: :solicitud
  get 'filtros/new'       => 'filtros#new',       as: :nuevo_filtro

  Rails.application.routes.draw do
    resources :filtros
    resources :alerta
    resources :recibos
    devise_for :users, :controllers =>  { :registrations => "my_devise/registrations" }
  end

end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  def solicitud
  end

  def index
    if current_user.AdminStatus == false && current_user.rol_user == nil
      redirect_to "/recibos/new"
    elsif current_user.rol_user == "cliente" || current_user.rol_user == "tercero"
      redirect_to "/vehiculos"
    end
  end
end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/views/layouts/_error.html.erb
<h4>No tienes autorización para ver este sitio.</h4>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-faded">
  <div class='container'>
    <a class='navbar-brand' href='/'>
      OTS<span class='light'>Services</span>
    </a>
    <button class="navbar-toggler hidden-sm-up pull-xs-right" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
      &#9776;
    </button>
    <ul class="nav navbar-nav pull-sm-right hidden-xs-down">
      <% if user_signed_in? %>

        <% if current_user && current_user.AdminStatus? %>
          <div class="dropdown nav-item">

            <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
              Reportes
            </button>

            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <%= link_to "Cliente", reporte_cliente_path, type: "button", class: "btn btn-default btn-block"%>
              <%= link_to "Vehiculo", reporte_vehiculo_path, type: "button", class: "btn btn-default btn-block"%>
              <%= link_to "Recibo", reporte_recibo_path, type: "button", class: "btn btn-default btn-block"%>
            </ulq>

          </div>

          <div class="dropdown nav-item">

            <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
              Dar de alta
            </button>

            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <%= link_to "Cliente", nuevo_cliente_path, type: "button", class: "btn btn-default btn-block"%>
              <%= link_to "Vehiculo", nuevo_vehiculo_path, type: "button", class: "btn btn-default btn-block"%>
              <%= link_to "Recibo", nuevo_recibo_path, type: "button", class: "btn btn-default btn-block"%>
              <%= link_to "Representante", '/users/sign_up', type: "button", class: "btn btn-default btn-block"%>
            </ul>

          </div>

        <% end %>

        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, type: "button", class: "btn btn-danger", :method => :delete%>
        </li>

      <% else %>

        <li class="nav-item">
          <%= link_to "Log In", new_user_session_path, type: "button", class: "btn btn-success" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OTSApplication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice || alert %>
      <% if notice %>
        <div class="alert-message alert alert-success" role="alert">
          <p class="notice"><%= notice %></p>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert-message alert alert-success" role="alert">
          <p class="alert"><%= alert %></p>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/index.html.erb
<body>

  <%= render 'layouts/navbar' %>
  <h2 style="text-align: center">Inicio</h2>
  <%= wicked_pdf_image_tag "/assets/images/pdflogo.png" %>
</body>

app/views/layouts/solicitud.html.erb
<body>
  <%= render 'layouts/navbar' %>
  <h2 style="text-align: center">Solicitar más producto:</h2>

  <div class="row">
    <div class="col-md-4 offset-md-4" style="text-align: center">
      <div class="form-signin">
        <br>
        <input type="text" class="form-control" placeholder="Nombre de producto">
        <br>
        <input type="number" class="form-control" placeholder="Cantidad">
        <br>
        <a href="index.html" class="btn btn-lg btn-success">Enviar</a>
      </div>
    </div>
  </div>
</body>